import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { RootProvider } from 'fumadocs-ui/provider/next'

import './globals.css'

const inter = Inter({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: {
    default: 'exjs-controllers',
    template: '%s | exjs-controllers'
  },
  description:
    'Declarative controllers, DTO validation, dependency injection, OpenAPI generation and Express bootstrap for TypeScript APIs.'
}

const basePath = process.env.DOCS_BASE_PATH ?? ''

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body className="min-h-screen">
        <RootProvider
          search={{
            // Static export: query the index generated by app/api/search/route.ts.
            // `api` must include basePath (GitHub Pages serves the site under
            // /exjs-controllers); Fumadocs' default does not add it.
            options: { type: 'static', api: `${basePath}/api/search` }
          }}
        >
          {children}
        </RootProvider>
      </body>
    </html>
  )
}
